version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node:
    image: subquerynetwork/subql-node-cosmos:v3.2.0
    ports:
      - 8080:3000
    depends_on:
      'postgres':
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - ${SUB_COMMAND:-}
      - -f=/app
      - --db-schema=app
      - --workers=4
      - --batch-size=30
      - --log-level=debug
      - --unsafe
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://subquery-node:3000/ready']
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      'postgres':
        condition: service_healthy
      'subquery-node':
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000

  stargaze:
    image: ${STARGAZE_IMAGE:-publicawesome/stargaze:12.0.0-arm.1}
    environment:
      - DENOM=ustars
      - CHAINID=testing
      - GAS_LIMIT=75000000
    ports:
      - '1317:1317'
      - '26656:26656'
      - '26657:26657'
      - '9090:9090'
    volumes:
      - .data/stargaze:/root
    entrypoint:
      [
        '/data/entry-point.sh',
        'stars16z43tjws3vw06ej9v7nrszu0ldsmn0eyjnjpu8',
        'stars1t08es9sxvjt3rmmkf426ks4ce528m0u84lyv92',
        'stars1x0nystpdqr9dtcy02wh4tcmhjxjlnk009ngcs8',
        'stars1v3fwgyw9kgtm08dpmfrlergxzxazwqa3qqxvd7',
        'stars1r98zsyt50k7yk86pf28xhdtf5yedkf7wm7nu0n',
      ]
    profiles:
      - localnet
