postgresql:
  global:
    storageClass: longhorn
  primary:
    initdb:
      scripts:
        00_init_extensions.sql: |
          CREATE EXTENSION IF NOT EXISTS btree_gist;
subquery:
  image: ghcr.io/ujulabs/infinity-indexer:latest
  imagePullSecret: ghcr-credentials
  chainId: 'stargaze-1'
  archiveEndpoint: https://rpc.full-nodes.stargaze-1.stargaze.build
  endpoint: https://rpc.stargaze-apis.com/
  startBlock: 10327462
  factoryMigrationHeight: 11669168
  pairMigrationHeight: 11669303
  targetBlock: 11669303
  createServicePod: true

graphql:
  image: onfinality/subql-query:latest
